export default {
  login: "تسجيل الدخول",
  username: "اسم المستخدم",
  password: "كلمة المرور",
  usernameWarning: "الرجاء ادخال اسم المستخدم",
  passwordWarning: "الرجاء ادخال كلمة المرور",
  rememberMe: "تذكرني",
  loginMessage: "تم تسجيل الدخول بنجاح",
  loginDescription: "اهلاً {username}",
  error: "حدث خطأ",
  newTab: "تبويب جديد",
  error500: "خطأ في المخدم",
  error400: "طلب خاطئ",
  home: "الرئيسية",
  searchPlaceholder: "بحث في القائمة الرئيسية",
  tableEmptyText: "لا يوجد بيانات",
  networkError: "لا يتوفر اتصال بالمخدم",
  alerts: "التنبيهات",
  notifications: "الإشعارات",
  messages: "الرسائل",
  favorite: "المفضلة",
  more: "المزيد",
  clickToUpload: "اضغط للرفع",
  search: "بحث",
  sortBy: "ترتيب حسب",
  sortAscending: "الترتيب تصاعدياً",
  sortDescending: "الترتيب تنازلياً",
  calculateRows: "حساب عدد جميع الأسطر",
  calculateRowsAlways: "حساب عدد الأسطر دائماً",
  export: "تصدير",
  savedFilters: "الفلاتر المحفوظة",
  apply: "تطبيق",
  delete: "حذف",
  restoreDefaultFilter: "استعادة الفلتر الإفتراضي",
  saveFilter: "حفظ الفلتر الحالي",
  confirmDeleteFilter: "هل انت متأكد انك تريد حذف هذا الفلتر ؟",
  ok: "نعم",
  no: "لا",
  save: "حفظ",
  cancel: "إلغاء",
  filterName: "اسم الفلتر",
  defaultFilter: "فلتر افتراضي ؟",
  savedSuccessfully: "تم الحفظ بنجاح",
  deleteSuccessfully: "تم الحذف بنجاح",
  addToFavorite: "إضافة الى المفضلة",
  deleteFromFavorite: "حذف من المفضلة",
  inFavoriteName: "الإسم داخل المفضلة",
  refresh: "تحديث الصفحة",
  edit: "تعديل",
  view: "عرض",
  add: "إضافة",
  download: "تحميل",
  confirm: "تأكيد",
  logout: "تسجيل الخروج",
  excel: "Excel",
  pdf: "PDF",
  errorUpload: "حدث خطأ في رفع الملف",
  loading: "جاري التحميل ...",
  dateButton:"اختر التاريخ",
  timeButton:"اختر الوقت",
  datetimeButton:" اختر التاريخ والوقت",
  next:"التالي",
  previous:"السابق",
  noOperations: "لا يوجد عمليات متاحة",
  pageNumber: "الصفحة الحالية",
  details:"تفاصيل"
};
